### ISSUE TITLE
基本用法在哪里？

### ISSUE THREAD

**Issue by geekmc** [DigDream/urp-python#1]

**Comment by dubuqingfeng** [comment]
刚完成了一键评估部分
你评估了没？
基本用法
查看学籍信息可以通过：
     python urpclient.py status -no 学号
然后输入密码，验证码。在urp.log文件里可以看到对应的html代码，现在还没解析，一会解析到控制台输出即可。
目前的代码查询成绩的是本学期成绩的地址，相对应改了以后既可以查询了，查询的目前只进行打印到urp.log文件中，很快就会解析到控制台的，使用了BeautifulSoup。
欢迎一块完善那些解析与判断的代码。

**Comment by geekmc** [comment]
。。评估了，验证码在哪里看？

**Comment by dubuqingfeng** [comment]
验证码目前是在image.jpg这个里，基本需要登录的操作，验证码会保存到这个文件里，然后打开输入上即可，后期可以考虑自动识别验证码。

**Comment by geekmc** [comment]
good

**Comment by geekmc** [comment]
在加一个本学期绩点计算

**Comment by dubuqingfeng** [comment]
嗯，最初的想法只是个查询成绩和一键评估功能。其他都好添加，花了几天的时间评估了。
